# Generated by Django 5.2.6 on 2025-09-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionistbackendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultationid', models.AutoField(primary_key=True, serialize=False)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistbackendapp.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('medicineprescriptionid', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctorbackendapp.consultation')),
            ],
        ),
    ]
