# Generated by Django 5.2.6 on 2025-09-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorbackendapp', '0001_initial'),
        ('pharmacistbackendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineprescription',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistbackendapp.medicine'),
        ),
    ]
