# Generated by Django 5.2.6 on 2025-09-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorbackendapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('medicinecategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('medicinecategoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unitmaster',
            fields=[
                ('unitid', models.AutoField(primary_key=True, serialize=False)),
                ('unitname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='doctorbackendapp.medicineprescription')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicineid', models.AutoField(primary_key=True, serialize=False)),
                ('medicinename', models.CharField(max_length=200)),
                ('manufacturedate', models.DateField()),
                ('expirydate', models.DateField()),
                ('unitquantity', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicinecategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistbackendapp.medicinecategory')),
                ('unitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistbackendapp.unitmaster')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('medicinestockid', models.AutoField(primary_key=True, serialize=False)),
                ('stockhand', models.IntegerField()),
                ('reorderlevel', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('issuance', models.IntegerField()),
                ('createddate', models.DateTimeField()),
                ('medicineid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistbackendapp.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistbackendapp.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacistbackendapp.bill')),
                ('prescription_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pharmacistbackendapp.prescriptionitem')),
            ],
        ),
    ]
