# Generated by Django 5.2.6 on 2025-09-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminbackendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('mobileno', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentdate', models.DateField()),
                ('tokenno', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminbackendapp.doctor')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistbackendapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billingid', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentdate', models.DateField()),
                ('consultationfee', models.IntegerField()),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistbackendapp.appointment')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistbackendapp.patient')),
            ],
        ),
    ]
