# Generated by Django 5.2.6 on 2025-09-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(max_length=500)),
                ('dob', models.DateField()),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('DOCTOR', 'Doctor'), ('PHARMACIST', 'Pharmacist')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminbackendapp.specialization')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminbackendapp.staff')),
            ],
        ),
    ]
